const btnEl = document.getElementById("btn")
const capsEl = document.getElementById("title")

const generatedTitle = [
  "Web-Based Inventory Management System",
"Online Reservation and Booking Platform",
"E-Learning Management System",
"Social Media Analytics Dashboard",
"Virtual Event Registration System",
"Web-Based Healthcare Appointment Scheduler",
"Employee Performance Evaluation Portal",
"Web-Based Library Catalog System",
"Online Voting and Polling Application",
"Task and Project Management Tool",
"Web-Based HR Recruitment System",
"E-Commerce Payment Gateway Integration",
"Online Food Ordering and Delivery Service",
"Web-Based Student Attendance Tracker",
"Customer Relationship Management (CRM) Software",
"Online Auction and Bidding Platform",
"Web-Based Ticket Reservation System",
"Digital Marketing Analytics Dashboard",
"Web-Based Property Rental Management",
"Online Quiz and Exam Management System",
"Web-Based Personal Finance Tracker",
"Appointment Scheduling for Salons and Spas",
"E-Library Management System",
"Online Event Ticketing and Registration",
"Web-Based Project Portfolio Management",
"Web-Based Real Estate Listing Platform",
"Online Course Registration System",
"Web-Based Inventory Tracking for Retailers",
"Expense Tracking and Budgeting Web App",
"Web-Based Travel Booking System",
"Online Customer Support and Helpdesk",
"Web-Based Time and Attendance System",
"Web-Based Restaurant Reservation System",
"Online Survey and Feedback Platform",
"E-Tourism and Travel Guide Website",
"Web-Based Asset Management System",
"Online Health and Fitness Tracker",
"Web-Based Task and Issue Tracker",
"E-Commerce Shopping Cart Application",
"Web-Based Vehicle Rental Management",
"Online Music Streaming Platform",
"Web-Based School Management System",
"Online Job Search and Recruitment Portal",
"Web-Based CRM for Small Businesses",
"Web-Based Medical Records Management",
"Online Event Planning and RSVP System",
"Web-Based Employee Leave Management",
"Web-Based Ticketing and Support System",
"Online Charity Donation Platform",
"Web-Based Personal Diary and Journal",
"Web-Based Project Expense Tracking",
"Online Language Learning Platform",
"Web-Based Hotel Reservation System",
"Web-Based Task Assignment and Tracking",
"Online Legal Document Management",
"Web-Based Event Calendar and Scheduler",
"Web-Based Pet Adoption and Shelter System",
"Online Stock Trading Platform",
"Web-Based Volunteer Management System",
"Web-Based Invoice and Billing System",
"Online Photography Portfolio Website",
"Web-Based Public Transportation Booking",
"Web-Based Grocery Delivery Service",
"Online Art Gallery and Sales Platform",
"Web-Based Inventory Demand Forecasting",
"Online Real-Time Chat Application",
"Web-Based Employee Training Platform",
"Online Dating and Matchmaking Service",
"Web-Based Freelancer Marketplace",
"Web-Based Restaurant Menu Ordering",
"Online Auction House Management",
"Web-Based Social Networking Platform",
"Web-Based Customer Feedback System",
"Online Sports League Management",
"Web-Based Fundraising and Crowdfunding",
"Web-Based Document Version Control",
"Online Political Campaign Management",
"Web-Based Task Automation Tool",
"Web-Based Healthcare Records Portal",
"Online Resume Builder and Job Portal",
"Web-Based Warehouse Management System",
"Online Video Streaming and Hosting",
"Web-Based Event Ticket Resale Platform",
"Web-Based Investment Portfolio Tracker",
"Online Home Energy Management",
"Web-Based Laboratory Information System",
"Web-Based Social Impact Reporting",
"Online Wedding Planning and RSVP",
"Web-Based Customer Loyalty Program",
"Web-Based Lost and Found System",
"Online Language Translation Service",
"Web-Based Investment Crowdsourcing",
"Web-Based Marketing Automation Tool",
"Online Healthcare Appointment Booking",
"Web-Based Equipment Maintenance Tracker",
"Web-Based Restaurant Reservation and Reviews",
"Online Car Rental and Booking Service",
"Web-Based Inventory Restocking System",
"Online Travel Itinerary Planner",
"Web-Based Legal Case Management",
"Web-Based Social Polling and Surveys",
"Online Dating Profile Analyzer",
"Web-Based Public Transportation Tracker",
"Online Charity Fund Distribution",
"Web-Based Pet Healthcare Records",
"Web-Based Home Security Monitoring",
"Online Sports Event Ticketing",
"Web-Based Real-Time Collaboration Tool",
"Web-Based Employee Benefits Management",
"Online Job Application Tracking System",
"Web-Based Vehicle Maintenance Scheduler",
"Online Music Collaboration Platform",
"Web-Based School Timetable Generator",
"Online Business Directory and Reviews",
"Web-Based Customer Order Tracking",
"Web-Based Medical Prescription Management",
"Online Event Marketing and Promotion",
"Web-Based Library Book Recommendation",
"Web-Based Fitness Class Booking",
"Online Legal Advice and Consultation",
"Web-Based Event Registration and RSVP",
"Web-Based Personal Recipe Collection",
"Online Stock Portfolio Analysis",
"Web-Based Volunteer Task Assignment",
"Online Invoice and Payment Reminder",
"Web-Based Public Transport Timetable",
"Online Grocery Shopping and Delivery",
"Web-Based Art Gallery Auctions",
"Web-Based Inventory Stocktake Tool",
"Online Real Estate Property Showcase",
"Web-Based Nonprofit Grant Management",
"Web-Based Document Collaboration Platform",
"Online Political Campaign Analytics",
"Web-Based Task Management and Tracking",
"Online Healthcare Prescription Refills",
"Web-Based Warehouse Inventory System",
"Online Video Content Management",
"Web-Based Event Venue Booking",
"Web-Based Investment Advisory Service",
"Online Home Energy Consumption Monitor",
"Web-Based Laboratory Test Result Viewer",
"Web-Based Social Impact Assessment",
"Online Wedding Guest RSVP",
"Web-Based Customer Feedback Analysis",
"Web-Based Lost and Found Database",
"Online Language Learning Community",
"Web-Based Investment Portfolio Analysis",
"Web-Based Marketing Campaign Management",
"Online Healthcare Telemedicine Platform",
"Web-Based Equipment Maintenance Alerts",
  "Optimizing Supply Chain Efficiency: A Data-Driven Approach",
"Enhancing Customer Experience with Predictive Analytics",
"Market Segmentation Analysis for Product Development",
"Improving Financial Forecasting Models for Profit Maximization",
"Exploring Data-Driven Marketing Strategies",
"Streamlining Inventory Management Using Data Analytics",
"Customer Churn Prediction and Retention Strategies",
"Data-Driven Decision-Making in Human Resources",
"Analyzing Sales Trends and Predicting Future Revenues",
"Enhancing Data Security and Privacy in Business Operations",
"Social Media Sentiment Analysis for Brand Reputation Management",
"Credit Risk Assessment for Lending Institutions",
"Supply Chain Network Optimization for Cost Reduction",
"Predictive Maintenance in Manufacturing",
"Market Basket Analysis for Retail Sales",
"A/B Testing and Conversion Rate Optimization",
"Improving Healthcare Analytics for Better Patient Outcomes",
"Strategic Pricing Analysis and Optimization",
"Employee Performance Evaluation and Incentive Design",
"Predicting Stock Market Trends Using Machine Learning",
"Data-Driven Fraud Detection and Prevention",
"Energy Consumption Analysis for Sustainable Practices",
"Sentiment Analysis in Financial News for Investment Insights",
"Optimizing E-commerce Recommendations",
"Web Traffic Analysis for SEO and Content Strategy",
"Data-Driven Insights for Cost Reduction in Manufacturing",
"Customer Lifetime Value Analysis",
"Financial Portfolio Management Using Data Analytics",
"Business Process Optimization with Process Mining",
"Market Entry Strategy Using Competitive Analysis",
"Anomaly Detection in Network Security",
"Text Analytics for Customer Feedback Insights",
"Data-Driven Product Development in the Tech Industry",
"Predictive Analytics for HR Talent Acquisition",
"Retail Inventory Optimization for Seasonal Demand",
"Healthcare Data Visualization for Decision Support",
"Data-Driven Approaches to Improve Customer Retention",
"Real-time Data Analysis for Disaster Response Planning",
"Evaluating the Impact of Marketing Campaigns",
"Economic Forecasting Using Time Series Analysis",
"Data-Driven Sustainability Reporting",
"Text Mining for Competitive Intelligence",
"Optimizing Call Center Operations",
"Sales Funnel Analysis and Conversion Rate Improvement",
"Predictive Analytics for Student Performance in Education",
"Data-Driven Compliance and Risk Management",
"Enhancing User Experience with User Behavior Analysis",
"Optimizing Logistics and Transportation Efficiency",
"Data-Driven Decision-Making for Nonprofit Organizations",
"Market Expansion Strategies Based on Data Insights",
"Sentiment Analysis of Social Media Data for Brands",
"Employee Engagement Analysis and Improvement",
"Inventory Demand Forecasting Using Machine Learning",
"Data-Driven Product Recommendations in E-commerce",
"Predictive Analytics for Healthcare Resource Allocation",
"Optimizing Procurement and Supplier Management",
"Enhancing Customer Support with Chatbot Analysis",
"Financial Data Visualization for Investment Decisions",
"Agricultural Yield Prediction and Farming Strategies",
"Data-Driven Fraud Detection in Financial Services",
"Analyzing User Behavior for Mobile App Optimization",
"Business Continuity Planning with Data Analytics",
"Evaluating Marketing Channel Effectiveness",
"Text Analytics for Political Campaign Strategy",
"Predictive Maintenance in Aerospace Industry",
"Data-Driven Risk Assessment in Insurance",
"Market Entry Strategies for International Expansion",
"Healthcare Claims Fraud Detection Using AI",
"Customer Segmentation for Personalized Marketing",
"Supply Chain Resilience Analysis",
"Energy Consumption Reduction Strategies for Businesses",
"Employee Attrition Prediction and Retention Planning",
"Credit Scoring Model Development",
"Optimizing Advertisement Allocation in Media",
"Predictive Analytics for Energy Consumption",
"Data-Driven Inventory Management in Retail",
"Cybersecurity Threat Analysis and Mitigation",
"Sentiment Analysis for Movie Box Office Predictions",
"Optimizing Warehouse Operations with Data Analytics",
"Data-Driven Product Development in Food Industry",
"Employee Productivity Improvement Using Data",
"Predictive Modeling for Loan Default Prediction",
"Data-Driven Marketing Attribution Modeling",
"Anomaly Detection in Healthcare Claims",
"Market Basket Analysis for Online Retailers",
"Data-Driven Strategies for Tourism and Hospitality",
"Social Media Influencer Analysis and Marketing",
"Supply Chain Risk Assessment and Mitigation",
"Energy Consumption Patterns in Smart Cities",
"User Behavior Analysis for Gaming Industry",
"Data-Driven Strategies for Educational Institutions",
"Evaluating the Impact of Online Ad Campaigns",
"Credit Card Fraud Detection with Machine Learning",
"Market Research and Product Launch Strategies",
"Predictive Analytics for Property Price Trends",
"Data-Driven Decision-Making for Local Government",
"Customer Sentiment Analysis in E-commerce",
"Optimizing Fleet Management with Data Analytics",
"Data-Driven Strategies for Sustainable Agriculture",
"Predictive Analytics for Public Health Trends"
]

function getcapstitle (){
  const index = Math.floor(Math.random()*generatedTitle.length)
  capsEl.innerHTML = generatedTitle[index]
}

getcapstitle()

btnEl.addEventListener("click", getcapstitle)
