const btnEl = document.getElementById("btn")
const capsEl = document.getElementById("title")

const generatedTitle = [
  "Web-Based Inventory Management System",
"Online Reservation and Booking Platform",
"E-Learning Management System",
"Social Media Analytics Dashboard",
"Virtual Event Registration System",
"Web-Based Healthcare Appointment Scheduler",
"Employee Performance Evaluation Portal",
"Web-Based Library Catalog System",
"Online Voting and Polling Application",
"Task and Project Management Tool",
"Web-Based HR Recruitment System",
"E-Commerce Payment Gateway Integration",
"Online Food Ordering and Delivery Service",
"Web-Based Student Attendance Tracker",
"Customer Relationship Management (CRM) Software",
"Online Auction and Bidding Platform",
"Web-Based Ticket Reservation System",
"Digital Marketing Analytics Dashboard",
"Web-Based Property Rental Management",
"Online Quiz and Exam Management System",
"Web-Based Personal Finance Tracker",
"Appointment Scheduling for Salons and Spas",
"E-Library Management System",
"Online Event Ticketing and Registration",
"Web-Based Project Portfolio Management",
"Web-Based Real Estate Listing Platform",
"Online Course Registration System",
"Web-Based Inventory Tracking for Retailers",
"Expense Tracking and Budgeting Web App",
"Web-Based Travel Booking System",
"Online Customer Support and Helpdesk",
"Web-Based Time and Attendance System",
"Web-Based Restaurant Reservation System",
"Online Survey and Feedback Platform",
"E-Tourism and Travel Guide Website",
"Web-Based Asset Management System",
"Online Health and Fitness Tracker",
"Web-Based Task and Issue Tracker",
"E-Commerce Shopping Cart Application",
"Web-Based Vehicle Rental Management",
"Online Music Streaming Platform",
"Web-Based School Management System",
"Online Job Search and Recruitment Portal",
"Web-Based CRM for Small Businesses",
"Web-Based Medical Records Management",
"Online Event Planning and RSVP System",
"Web-Based Employee Leave Management",
"Web-Based Ticketing and Support System",
"Online Charity Donation Platform",
"Web-Based Personal Diary and Journal",
"Web-Based Project Expense Tracking",
"Online Language Learning Platform",
"Web-Based Hotel Reservation System",
"Web-Based Task Assignment and Tracking",
"Online Legal Document Management",
"Web-Based Event Calendar and Scheduler",
"Web-Based Pet Adoption and Shelter System",
"Online Stock Trading Platform",
"Web-Based Volunteer Management System",
"Web-Based Invoice and Billing System",
"Online Photography Portfolio Website",
"Web-Based Public Transportation Booking",
"Web-Based Grocery Delivery Service",
"Online Art Gallery and Sales Platform",
"Web-Based Inventory Demand Forecasting",
"Online Real-Time Chat Application",
"Web-Based Employee Training Platform",
"Online Dating and Matchmaking Service",
"Web-Based Freelancer Marketplace",
"Web-Based Restaurant Menu Ordering",
"Online Auction House Management",
"Web-Based Social Networking Platform",
"Web-Based Customer Feedback System",
"Online Sports League Management",
"Web-Based Fundraising and Crowdfunding",
"Web-Based Document Version Control",
"Online Political Campaign Management",
"Web-Based Task Automation Tool",
"Web-Based Healthcare Records Portal",
"Online Resume Builder and Job Portal",
"Web-Based Warehouse Management System",
"Online Video Streaming and Hosting",
"Web-Based Event Ticket Resale Platform",
"Web-Based Investment Portfolio Tracker",
"Online Home Energy Management",
"Web-Based Laboratory Information System",
"Web-Based Social Impact Reporting",
"Online Wedding Planning and RSVP",
"Web-Based Customer Loyalty Program",
"Web-Based Lost and Found System",
"Online Language Translation Service",
"Web-Based Investment Crowdsourcing",
"Web-Based Marketing Automation Tool",
"Online Healthcare Appointment Booking",
"Web-Based Equipment Maintenance Tracker",
"Web-Based Restaurant Reservation and Reviews",
"Online Car Rental and Booking Service",
"Web-Based Inventory Restocking System",
"Online Travel Itinerary Planner",
"Web-Based Legal Case Management",
"Web-Based Social Polling and Surveys",
"Online Dating Profile Analyzer",
"Web-Based Public Transportation Tracker",
"Online Charity Fund Distribution",
"Web-Based Pet Healthcare Records",
"Web-Based Home Security Monitoring",
"Online Sports Event Ticketing",
"Web-Based Real-Time Collaboration Tool",
"Web-Based Employee Benefits Management",
"Online Job Application Tracking System",
"Web-Based Vehicle Maintenance Scheduler",
"Online Music Collaboration Platform",
"Web-Based School Timetable Generator",
"Online Business Directory and Reviews",
"Web-Based Customer Order Tracking",
"Web-Based Medical Prescription Management",
"Online Event Marketing and Promotion",
"Web-Based Library Book Recommendation",
"Web-Based Fitness Class Booking",
"Online Legal Advice and Consultation",
"Web-Based Event Registration and RSVP",
"Web-Based Personal Recipe Collection",
"Online Stock Portfolio Analysis",
"Web-Based Volunteer Task Assignment",
"Online Invoice and Payment Reminder",
"Web-Based Public Transport Timetable",
"Online Grocery Shopping and Delivery",
"Web-Based Art Gallery Auctions",
"Web-Based Inventory Stocktake Tool",
"Online Real Estate Property Showcase",
"Web-Based Nonprofit Grant Management",
"Web-Based Document Collaboration Platform",
"Online Political Campaign Analytics",
"Web-Based Task Management and Tracking",
"Online Healthcare Prescription Refills",
"Web-Based Warehouse Inventory System",
"Online Video Content Management",
"Web-Based Event Venue Booking",
"Web-Based Investment Advisory Service",
"Online Home Energy Consumption Monitor",
"Web-Based Laboratory Test Result Viewer",
"Web-Based Social Impact Assessment",
"Online Wedding Guest RSVP",
"Web-Based Customer Feedback Analysis",
"Web-Based Lost and Found Database",
"Online Language Learning Community",
"Web-Based Investment Portfolio Analysis",
"Web-Based Marketing Campaign Management",
"Online Healthcare Telemedicine Platform",
"Web-Based Equipment Maintenance Alerts"
]

function getcapstitle (){
  const index = Math.floor(Math.random()*generatedTitle.length)
  capsEl.innerHTML = generatedTitle[index]
}

getcapstitle()

btnEl.addEventListener("click", getcapstitle)